# -*- coding: utf-8 -*-
"""Mapapeliculas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTVLe0c4YbduZ9q7zB2fJcXVLg7cN-kT
"""

from google.colab import files
import pandas as pd
import folium

uploaded = files.upload()

df = pd.read_excel("peliculas_mapa_final.xlsx")

if "Coordenada" in df.columns:
    try:
        df[['Latitud', 'Longitud']] = df['Coordenada'].str.split(',', expand=True)
    except:
        pass

df["Latitud"] = pd.to_numeric(df["Latitud"], errors="coerce")
df["Longitud"] = pd.to_numeric(df["Longitud"], errors="coerce")

df = df.dropna(subset=["Latitud", "Longitud"])

mapa = folium.Map(location=[20,0], zoom_start=2)

for _, row in df.iterrows():
    popup_html = (
        f"<b>{row['Película']}</b><br>"
        f"Producción: {row['Producción']}<br>"
        f"Latitud: {row['Latitud']}<br>"
        f"Longitud: {row['Longitud']}"
    )

    folium.Marker(
        location=[row["Latitud"], row["Longitud"]],
        popup=popup_html
    ).add_to(mapa)

mapa