# -*- coding: utf-8 -*-
"""Trabajo final_peliculas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0HTaak4eCuUFBC2NZKyfn7sofkNVPii
"""



import pandas as pd
#Subes el archivo
from google.colab import files
archivo = files.upload()
#Que lea el CSV
df = pd.read_excel('peliculas_final.xlsx')

print("Columnas del archivo:")
print(df.columns.tolist())

# Muestra las primeras filas
print("\nPrimeras filas:")
print(df.head())

#Darle la bienvenida y opciones al usuario
print("Bienvenido a nuestra página de películas")
print("Opciones: Tristeza, Alegría, Miedo, Amor, Inspiradora")

#Preguntarle al usuario la emoción
eleccion = input("\n¿Qué emoción te gustaría sentir hoy?: ")

#Filtrar las filas que coinciden con la emoción elegida
resultados = df[df["Emociones"] == eleccion]

print(f"\n Películas que pueden hacerte experimentar {eleccion}:\n")

for nombre in resultados["Nombre"]:
    print(f"- {nombre}")
# for i in range(len(df)):
 #   print(f"Nombre: {resultados['Nombre']}")

#codigo de barras para grafico de tristeza
pelis_triste=df[df["Emociones"].str.lower() == "tristeza"]
pelis_triste

generos=(
    pelis_triste["Género"]
    .str.split(",", expand=False)
    .explode()
    .str.strip()
)

genero_cuentas_triste= generos.value_counts()
genero_cuentas_triste

import matplotlib.pyplot as plt
genero_cuentas_triste.plot(kind='bar', figsize=(10, 6), color='blue')
plt.title("Géneros de Películas con Sentimiento de Tristeza")
plt.xlabel("Género")
plt.ylabel("Cantidad de Películas")
plt.xticks(rotation=75)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

#grafico de peliculas alegres
pelis_alegre=df[df["Emociones"].str.lower() == "alegría"]

generos_alegre=(
    pelis_alegre["Género"]
    .str.split(",", expand=False)
    .explode()
    .str.strip()
)

genero_cuenta_alegre=generos_alegre.value_counts()
genero_cuenta_alegre

import matplotlib.pyplot as plt
genero_cuenta_alegre.plot(kind='bar', figsize=(10, 6), color='yellow')
plt.title("Géneros de Películas con Sentimiento de Alegria")
plt.xlabel("Género")
plt.ylabel("Cantidad de Películas")
plt.xticks(rotation=75)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

#graficos pelis amor
pelis_amor=df[df["Emociones"].str.lower() == "amor"]

generos_amor=(
    pelis_amor["Género"]
    .str.split(",", expand=False)
    .explode()
    .str.strip()
)

genero_cuenta_amor=generos_amor.value_counts()
genero_cuenta_amor



import matplotlib.pyplot as plt
genero_cuenta_amor.plot(kind='bar', figsize=(10, 6), color='red')
plt.title("Géneros de Películas con Sentimiento de Amor")
plt.xlabel("Género")
plt.ylabel("Cantidad de Películas")
plt.xticks(rotation=75)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()



#graficos pelis Miedo
pelis_miedo=df[df["Emociones"].str.lower() == "miedo"]

generos_miedo=(
    pelis_miedo["Género"]
    .str.split(",", expand=False)
    .explode()
    .str.strip()
)

genero_cuenta_miedo=generos_miedo.value_counts()
genero_cuenta_miedo

import matplotlib.pyplot as plt
genero_cuenta_miedo.plot(kind='bar', figsize=(10, 6), color='purple')
plt.title("Géneros de Películas con Sentimiento de Miedo")
plt.xlabel("Género")
plt.ylabel("Cantidad de Películas")
plt.xticks(rotation=75)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

#graficos pelis Motivacion
pelis_motivacion=df[df["Emociones"].str.lower() == "inspiradoras"]

genero_motiva=(
    pelis_motivacion["Género"]
    .str.split(",", expand=False)
    .explode()
    .str.strip()
)

genero_cuenta_motiva=genero_motiva.value_counts()
genero_cuenta_motiva

import matplotlib.pyplot as plt
genero_cuenta_motiva.plot(kind='bar', figsize=(10, 6), color='green')
plt.title("Géneros de Películas con Sentimiento de Motivacion")
plt.xlabel("Género")
plt.ylabel("Cantidad de Películas")
plt.xticks(rotation=75)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

import random

# Seleccionar un nombre de película al azar desde la columna "Nombre"
pelicula = random.choice(df["Nombre"]).upper()

print("🎬 Bienvenido al juego del Ahorcado de Películas 🎬")
print("Adivina el nombre de la película letra por letra.\n")

# Crear una versión oculta con guiones (pero conservando espacios)
progreso = ["_" if letra.isalpha() else letra for letra in pelicula]

vidas = 6
letras_intentadas = []

while vidas > 0 and "_" in progreso:

    print("\nPelícula:", " ".join(progreso))
    print(f"Vidas restantes: {vidas}")
    print("Letras usadas:", ", ".join(letras_intentadas))

    intento = input("\nIngresa una letra: ").upper()

    # Validaciones
    if len(intento) != 1 or not intento.isalpha():
        print("Ingresa SOLO una letra.")
        continue

    if intento in letras_intentadas:
        print("⚠ Ya intentaste esa letra.")
        continue

    letras_intentadas.append(intento)

    # Revisar si la letra está en el título
    if intento in pelicula:
        print("¡Correcto!")
        for i, letra in enumerate(pelicula):
            if letra == intento:
                progreso[i] = intento
    else:
        print("Incorrecto")
        vidas -= 1

# Resultado final
if "_" not in progreso:
    print("\n🎉 ¡GANASTE! La película era:", pelicula)
else:
    print("\n💀 Te quedaste sin vidas. La película era:", pelicula)

#mapa para peliculas de netlix

import pandas as pd
#Subes el archivo
from google.colab import files
archivo = files.upload()
#Que lea el CSV
df_mapas= pd.read_excel('peliculas_mapa_final.xlsx')

df_mapas

import folium

m= folium.Map(location=[20, 0], zoom_start=2)

# Darle la bienvenida y opciones al usuario
print("Bienvenido a nuestra página de películas")
print("Opciones de emociones: Tristeza, Alegría, Miedo, Amor, Inspiradora")

# Preguntarle al usuario la emoción
eleccion = input("\n¿Qué emoción te gustaría sentir hoy?: ")

# Preguntar duración
print("\nOpciones de duración:")
print("1. Menos de 120 minutos")
print("2. Entre 120 y 150 minutos")
print("3. Más de 150 minutos")

op_tiempo = input("¿Qué duración prefieres?: ")

# Convertir la opción a filtro
if op_tiempo == "1":
    filtro_tiempo = df["Duración"] < 120
elif op_tiempo == "2":
    filtro_tiempo = (df["Duración"] >= 120) & (df["Duración"] <= 150)
elif op_tiempo == "3":
    filtro_tiempo = df["Duración"] > 150
else:
    print("\nOpción de tiempo inválida.")
    filtro_tiempo = None

# Si el filtro de tiempo es válido, combinar SENTIMIENTO + DURACIÓN
if filtro_tiempo is not None:
    resultados = df[(df["Emociones"] == eleccion) & (filtro_tiempo)]

    print(f"\nPelículas que coinciden con '{eleccion}' y el tiempo elegido:\n")

    if len(resultados) == 0:
        print("No se encontraron películas con esos filtros :(")
    else:
        for nombre in resultados["Nombre"]:
            print(f"- {nombre}")